return {
  ForgottenQuest = {
    [1] = {
      Reward = {
        Exp = 47000000,
        Beli = 12250
      },
      Task = {
        ["Sea Soldier"] = 8
      },
      Name = "Sea Soldier",
      LevelReq = 1425
    },
    [2] = {
      Reward = {
        Exp = 49000000,
        Beli = 12500
      },
      Task = {
        ["Water Fighter"] = 8
      },
      Name = "Water Fighter",
      LevelReq = 1450
    },
    [3] = {
      Reward = {
        Exp = 51000000,
        Beli = 12500
      },
      Task = {
        ["Tide Keeper"] = 1
      },
      Name = "Tide Keeper",
      LevelReq = 1475
    }
  },
  ["HauntedQuest2"] = {
    [1] = {
      Reward = {
        Exp = 96000000,
        Beli = 13500
      },
      Task = {
        ["Demonic Soul"] = 8
      },
      Name = "Demonic Soul",
      LevelReq = 2025
    },
    [2] = {
      Reward = {
        Exp = 98500000,
        Beli = 13750
      },
      Task = {
        ["Posessed Mummy"] = 8
      },
      Name = "Posessed Mummy",
      LevelReq = 2050
    }
  },
  SkyQuest = {
    [1] = {
      Reward = {
        Exp = 315000,
        Beli = 7000
      },
      Task = {
        ["Sky Bandit"] = 7
      },
      Name = "Sky Bandit",
      LevelReq = 150
    },
    [2] = {
      Reward = {
        Exp = 450000,
        Beli = 7500
      },
      Task = {
        ["Dark Master"] = 8
      },
      Name = "Dark Master",
      LevelReq = 175
    }
  },
  ImpelQuest = {
    [1] = {
      Reward = {
        Exp = 850000,
        Beli = 6000
      },
      Task = {
        Warden = 1
      },
      Name = "Warden",
      LevelReq = 220
    },
    [2] = {
      Reward = {
        Exp = 1000000,
        Beli = 10000
      },
      Task = {
        ["Chief Warden"] = 1
      },
      Name = "Chief Warden",
      LevelReq = 230
    },
    [3] = {
      Reward = {
        Exp = 1600000,
        Beli = 15000
      },
      Task = {
        Swan = 1
      },
      Name = "Swan",
      LevelReq = 240
    }
  },
  ["TikiQuest2"] = {
    [1] = {
      Reward = {
        Exp = 137000000,
        Beli = 15250
      },
      Task = {
        ["Sun-kissed Warrior"] = 8
      },
      Name = "Sun-kissed Warrior",
      LevelReq = 2500
    },
    [2] = {
      Reward = {
        Exp = 139000000,
        Beli = 15500
      },
      Task = {
        ["Isle Champion"] = 8
      },
      Name = "Isle Champion",
      LevelReq = 2525
    }
  },
  FishmanQuest = {
    [1] = {
      Reward = {
        Exp = 3050000,
        Beli = 8750
      },
      Task = {
        ["Fishman Warrior"] = 8
      },
      Name = "Fishman Warrior",
      LevelReq = 375
    },
    [2] = {
      Reward = {
        Exp = 3350000,
        Beli = 9000
      },
      Task = {
        ["Fishman Commando"] = 7
      },
      Name = "Fishman Commando",
      LevelReq = 400
    },
    [3] = {
      Reward = {
        Exp = 4250000,
        Beli = 15000
      },
      Task = {
        ["Fishman Lord"] = 1
      },
      Name = "Fishman Lord",
      LevelReq = 425
    }
  },
  ["DeepForestIsland3"] = {
    [1] = {
      Reward = {
        Exp = 73000000,
        Beli = 13000
      },
      Task = {
        ["Fishman Raider"] = 8
      },
      Name = "Fishman Raider",
      LevelReq = 1775
    },
    [2] = {
      Reward = {
        Exp = 75500000,
        Beli = 15000
      },
      Task = {
        ["Fishman Captain"] = 8
      },
      Name = "Fishman Captain",
      LevelReq = 1800
    }
  },
  ["CandyQuest1"] = {
    [1] = {
      Reward = {
        Exp = 129000000,
        Beli = 14950
      },
      Task = {
        ["Candy Pirate"] = 8
      },
      Name = "Candy Pirate",
      LevelReq = 2400
    },
    [2] = {
      Reward = {
        Exp = 131000000,
        Beli = 15000
      },
      Task = {
        ["Snow Demon"] = 8
      },
      Name = "Snow Demon",
      LevelReq = 2425
    }
  },
  FireSideQuest = {
    [1] = {
      Reward = {
        Exp = 29000000,
        Beli = 12250
      },
      Task = {
        ["Magma Ninja"] = 8
      },
      Name = "Magma Ninja",
      LevelReq = 1175
    },
    [2] = {
      Reward = {
        Exp = 31000000,
        Beli = 12500
      },
      Task = {
        ["Lava Pirate"] = 8
      },
      Name = "Lava Pirate",
      LevelReq = 1200
    }
  },
  CitizenQuest = {
    [1] = {
      MeetsRequirements = function(Val1) --[[ MeetsRequirements ]]end,
      Name = "Town Raid",
      OnComplete = function(Val1) --[[ OnComplete ]]end,
      Reward = {
        Exp = 250000000,
        Beli = 100000
      },
      Task = {
        ["Forest Pirate"] = 50
      },
      LevelReq = 1800
    }
  },
  JungleQuest = {
    [1] = {
      Reward = {
        Exp = 2300,
        Beli = 800
      },
      Task = {
        Monkey = 6
      },
      Name = "Monkeys",
      LevelReq = 10
    },
    [2] = {
      Reward = {
        Exp = 4500,
        Beli = 1200
      },
      Task = {
        Gorilla = 8
      },
      Name = "Gorillas",
      LevelReq = 15
    },
    [3] = {
      Reward = {
        Exp = 9500,
        Beli = 2000
      },
      Task = {
        ["The Gorilla King"] = 1
      },
      Name = "Gorilla King",
      LevelReq = 20
    }
  },
  FountainQuest = {
    [1] = {
      Reward = {
        Exp = 7500000,
        Beli = 10000
      },
      Task = {
        ["Galley Pirate"] = 8
      },
      Name = "Galley Pirate",
      LevelReq = 625
    },
    [2] = {
      Reward = {
        Exp = 8500000,
        Beli = 10000
      },
      Task = {
        ["Galley Captain"] = 9
      },
      Name = "Galley Captain",
      LevelReq = 650
    },
    [3] = {
      Reward = {
        Exp = 10000000,
        Beli = 20000
      },
      Task = {
        Cyborg = 1
      },
      Name = "Cyborg",
      LevelReq = 675
    }
  },
  DesertQuest = {
    [1] = {
      Reward = {
        Exp = 45000,
        Beli = 4000
      },
      Task = {
        ["Desert Bandit"] = 8
      },
      Name = "Desert Bandit",
      LevelReq = 60
    },
    [2] = {
      Reward = {
        Exp = 65000,
        Beli = 4500
      },
      Task = {
        ["Desert Officer"] = 6
      },
      Name = "Desert Officer",
      LevelReq = 75
    }
  },
  SnowQuest = {
    [1] = {
      Reward = {
        Exp = 90000,
        Beli = 5000
      },
      Task = {
        ["Snow Bandit"] = 7
      },
      Name = "Snow Bandit",
      LevelReq = 90
    },
    [2] = {
      Reward = {
        Exp = 150000,
        Beli = 5500
      },
      Task = {
        Snowman = 8
      },
      Name = "Snowman",
      LevelReq = 100
    },
    [3] = {
      Reward = {
        Exp = 220000,
        Beli = 10000
      },
      Task = {
        Yeti = 1
      },
      Name = "Yeti",
      LevelReq = 105
    }
  },
  MarineTreeIsland = {
    [1] = {
      Reward = {
        Exp = 68000000,
        Beli = 13000
      },
      Task = {
        ["Marine Commodore"] = 8
      },
      Name = "Marine Commodore",
      LevelReq = 1700
    },
    [2] = {
      Reward = {
        Exp = 70500000,
        Beli = 15000
      },
      Task = {
        ["Marine Rear Admiral"] = 8
      },
      Name = "Marine Rear Admiral",
      LevelReq = 1725
    },
    [3] = {
      Reward = {
        Exp = 78000000,
        Beli = 35000
      },
      Task = {
        ["Kilo Admiral"] = 1
      },
      Name = "Kilo Admiral",
      LevelReq = 1750
    }
  },
  ["HauntedQuest1"] = {
    [1] = {
      Reward = {
        Exp = 91000000,
        Beli = 13000
      },
      Task = {
        ["Reborn Skeleton"] = 8
      },
      Name = "Reborn Skeleton",
      LevelReq = 1975
    },
    [2] = {
      Reward = {
        Exp = 93500000,
        Beli = 13250
      },
      Task = {
        ["Living Zombie"] = 8
      },
      Name = "Living Zombie",
      LevelReq = 2000
    }
  },
  DeepForestIsland = {
    [1] = {
      Reward = {
        Exp = 78000000,
        Beli = 13000
      },
      Task = {
        ["Forest Pirate"] = 8
      },
      Name = "Forest Pirate",
      LevelReq = 1825
    },
    [2] = {
      Reward = {
        Exp = 81000000,
        Beli = 13000
      },
      Task = {
        ["Mythological Pirate"] = 8
      },
      Name = "Mythological Pirate",
      LevelReq = 1850
    },
    [3] = {
      Reward = {
        Exp = 90000000,
        Beli = 40000
      },
      Task = {
        ["Captain Elephant"] = 1
      },
      Name = "Captain Elephant",
      LevelReq = 1875
    }
  },
  ["Area2Quest"] = {
    [1] = {
      Reward = {
        Exp = 11500000,
        Beli = 10750
      },
      Task = {
        ["Swan Pirate"] = 8
      },
      Name = "Swan Pirate",
      LevelReq = 775
    },
    [2] = {
      Reward = {
        Exp = 13000000,
        Beli = 11000
      },
      Task = {
        ["Factory Staff"] = 8
      },
      Name = "Factory Staff",
      LevelReq = 800
    },
    [3] = {
      Reward = {
        Exp = 16000000,
        Beli = 25000
      },
      Task = {
        Jeremy = 1
      },
      Name = "Jeremy",
      LevelReq = 850
    }
  },
  ["Area1Quest"] = {
    [1] = {
      Reward = {
        Exp = 8750000,
        Beli = 10250
      },
      Task = {
        Raider = 8
      },
      Name = "Raider",
      LevelReq = 700
    },
    [2] = {
      Reward = {
        Exp = 9750000,
        Beli = 10500
      },
      Task = {
        Mercenary = 8
      },
      Name = "Mercenary",
      LevelReq = 725
    },
    [3] = {
      Reward = {
        Exp = 12500000,
        Beli = 25000
      },
      Task = {
        Diamond = 1
      },
      Name = "Diamond",
      LevelReq = 750
    }
  },
  ZombieQuest = {
    [1] = {
      Reward = {
        Exp = 19000000,
        Beli = 11750
      },
      Task = {
        Zombie = 8
      },
      Name = "Zombie",
      LevelReq = 950
    },
    [2] = {
      Reward = {
        Exp = 20500000,
        Beli = 12000
      },
      Task = {
        Vampire = 8
      },
      Name = "Vampire",
      LevelReq = 975
    }
  },
  ["TikiQuest1"] = {
    [1] = {
      Reward = {
        Exp = 133000000,
        Beli = 15100
      },
      Task = {
        ["Isle Outlaw"] = 8
      },
      Name = "Isle Outlaw",
      LevelReq = 2450
    },
    [2] = {
      Reward = {
        Exp = 135000000,
        Beli = 15200
      },
      Task = {
        ["Island Boy"] = 8
      },
      Name = "Island Boy",
      LevelReq = 2475
    }
  },
  ["ChocQuest2"] = {
    [1] = {
      Reward = {
        Exp = 125000000,
        Beli = 14800
      },
      Task = {
        ["Sweet Thief"] = 8
      },
      Name = "Sweet Thief",
      LevelReq = 2350
    },
    [2] = {
      Reward = {
        Exp = 127500000,
        Beli = 14900
      },
      Task = {
        ["Candy Rebel"] = 8
      },
      Name = "Candy Rebel",
      LevelReq = 2375
    }
  },
  ["ChocQuest1"] = {
    [1] = {
      Reward = {
        Exp = 120000000,
        Beli = 14600
      },
      Task = {
        ["Cocoa Warrior"] = 8
      },
      Name = "Cocoa Warrior",
      LevelReq = 2300
    },
    [2] = {
      Reward = {
        Exp = 122500000,
        Beli = 14700
      },
      Task = {
        ["Chocolate Bar Battler"] = 8
      },
      Name = "Chocolate Bar Battler",
      LevelReq = 2325
    }
  },
  ["DeepForestIsland2"] = {
    [1] = {
      Reward = {
        Exp = 85000000,
        Beli = 13000
      },
      Task = {
        ["Jungle Pirate"] = 8
      },
      Name = "Jungle Pirate",
      LevelReq = 1900
    },
    [2] = {
      Reward = {
        Exp = 87500000,
        Beli = 15000
      },
      Task = {
        ["Musketeer Pirate"] = 8
      },
      Name = "Musketeer Pirate",
      LevelReq = 1925
    },
    [3] = {
      Reward = {
        Exp = 100000000,
        Beli = 50000
      },
      Task = {
        ["Beautiful Pirate"] = 1
      },
      Name = "Beautiful Pirate",
      LevelReq = 1950
    }
  },
  ["AmazonQuest2"] = {
    [1] = {
      Reward = {
        Exp = 62500000,
        Beli = 13000
      },
      Task = {
        ["Female Islander"] = 8
      },
      Name = "Female Islander",
      LevelReq = 1625
    },
    [2] = {
      Reward = {
        Exp = 64500000,
        Beli = 15000
      },
      Task = {
        ["Giant Islander"] = 8
      },
      Name = "Giant Islander",
      LevelReq = 1650
    },
    [3] = {
      Reward = {
        Exp = 70000000,
        Beli = 30000
      },
      Task = {
        ["Island Empress"] = 1
      },
      Name = "Island Empress",
      LevelReq = 1675
    }
  },
  ["CakeQuest2"] = {
    [1] = {
      Reward = {
        Exp = 115000000,
        Beli = 14400
      },
      Task = {
        ["Baking Staff"] = 8
      },
      Name = "Baking Staff",
      LevelReq = 2250
    },
    [2] = {
      Reward = {
        Exp = 117500000,
        Beli = 14500
      },
      Task = {
        ["Head Baker"] = 8
      },
      Name = "Head Baker",
      LevelReq = 2275
    }
  },
  PrisonerQuest = {
    [1] = {
      Reward = {
        Exp = 550000,
        Beli = 7000
      },
      Task = {
        Prisoner = 8
      },
      Name = "Prisoner",
      LevelReq = 190
    },
    [2] = {
      Reward = {
        Exp = 780000,
        Beli = 7500
      },
      Task = {
        ["Dangerous Prisoner"] = 8
      },
      Name = "Dangerous Prisoner",
      LevelReq = 210
    }
  },
  ["MarineQuest3"] = {
    [1] = {
      Reward = {
        Exp = 15000000,
        Beli = 11250
      },
      Task = {
        ["Marine Lieutenant"] = 8
      },
      Name = "Marine Lieutenant",
      LevelReq = 875
    },
    [2] = {
      Reward = {
        Exp = 16500000,
        Beli = 11500
      },
      Task = {
        ["Marine Captain"] = 9
      },
      Name = "Marine Captain",
      LevelReq = 900
    },
    [3] = {
      Reward = {
        Exp = 19000000,
        Beli = 25000
      },
      Task = {
        Fajita = 1
      },
      Name = "Fajita",
      LevelReq = 925
    }
  },
  ["BanditQuest1"] = {
    [1] = {
      Reward = {
        Exp = 300,
        Beli = 350
      },
      Task = {
        Bandit = 5
      },
      Name = "Bandits",
      LevelReq = 0
    }
  },
  ["CakeQuest1"] = {
    [1] = {
      Reward = {
        Exp = 110000000,
        Beli = 14200
      },
      Task = {
        ["Cookie Crafter"] = 8
      },
      Name = "Cookie Crafter",
      LevelReq = 2200
    },
    [2] = {
      Reward = {
        Exp = 112500000,
        Beli = 14300
      },
      Task = {
        ["Cake Guard"] = 8
      },
      Name = "Cake Guard",
      LevelReq = 2225
    }
  },
  MagmaQuest = {
    [1] = {
      Reward = {
        Exp = 1700000,
        Beli = 8250
      },
      Task = {
        ["Military Soldier"] = 7
      },
      Name = "Mil. Soldier",
      LevelReq = 300
    },
    [2] = {
      Reward = {
        Exp = 2000000,
        Beli = 8500
      },
      Task = {
        ["Military Spy"] = 8
      },
      Name = "Mil. Spy",
      LevelReq = 325
    },
    [3] = {
      Reward = {
        Exp = 3000000,
        Beli = 15000
      },
      Task = {
        ["Magma Admiral"] = 1
      },
      Name = "Magma Admiral",
      LevelReq = 350
    }
  },
  IceCreamIslandQuest = {
    [1] = {
      Reward = {
        Exp = 105000000,
        Beli = 14200
      },
      Task = {
        ["Ice Cream Chef"] = 8
      },
      Name = "Ice Cream Chef",
      LevelReq = 2125
    },
    [2] = {
      Reward = {
        Exp = 107500000,
        Beli = 14300
      },
      Task = {
        ["Ice Cream Commander"] = 8
      },
      Name = "Ice Cream Commander",
      LevelReq = 2150
    },
    [3] = {
      Reward = {
        Exp = 112500000,
        Beli = 30000
      },
      Task = {
        ["Cake Queen"] = 1
      },
      Name = "Cake Queen",
      LevelReq = 2175
    }
  },
  ["ShipQuest2"] = {
    [1] = {
      Reward = {
        Exp = 37500000,
        Beli = 12250
      },
      Task = {
        ["Ship Steward"] = 8
      },
      Name = "Ship Steward",
      LevelReq = 1300
    },
    [2] = {
      Reward = {
        Exp = 39500000,
        Beli = 12500
      },
      Task = {
        ["Ship Officer"] = 8
      },
      Name = "Ship Officer",
      LevelReq = 1325
    }
  },
  MarineQuest = {
    [1] = {
      Reward = {
        Exp = 300,
        Beli = 350
      },
      Task = {
        Trainee = 5
      },
      Name = "Trainees",
      LevelReq = 0
    }
  },
  ColosseumQuest = {
    [1] = {
      Reward = {
        Exp = 1100000,
        Beli = 7000
      },
      Task = {
        ["Toga Warrior"] = 7
      },
      Name = "Toga Warrior",
      LevelReq = 250
    },
    [2] = {
      Reward = {
        Exp = 1300000,
        Beli = 7500
      },
      Task = {
        Gladiator = 8
      },
      Name = "Gladiator",
      LevelReq = 275
    }
  },
  IceSideQuest = {
    [1] = {
      Reward = {
        Exp = 25500000,
        Beli = 12250
      },
      Task = {
        ["Lab Subordinate"] = 8
      },
      Name = "Lab Subordinate",
      LevelReq = 1100
    },
    [2] = {
      Reward = {
        Exp = 27000000,
        Beli = 12500
      },
      Task = {
        ["Horned Warrior"] = 9
      },
      Name = "Horned Warrior",
      LevelReq = 1125
    },
    [3] = {
      Reward = {
        Exp = 32500000,
        Beli = 20000
      },
      Task = {
        ["Smoke Admiral"] = 1
      },
      Name = "Smoke Admiral",
      LevelReq = 1150
    }
  },
  ["SkyExp2Quest"] = {
    [1] = {
      Reward = {
        Exp = 5800000,
        Beli = 9500
      },
      Task = {
        ["Royal Squad"] = 8
      },
      Name = "Royal Squad",
      LevelReq = 525
    },
    [2] = {
      Reward = {
        Exp = 6300000,
        Beli = 9750
      },
      Task = {
        ["Royal Soldier"] = 8
      },
      Name = "Royal Soldier",
      LevelReq = 550
    },
    [3] = {
      Reward = {
        Exp = 8000000,
        Beli = 20000
      },
      Task = {
        ["Thunder God"] = 1
      },
      Name = "Thunder God",
      LevelReq = 575
    }
  },
  ["MarineQuest2"] = {
    [1] = {
      Reward = {
        Exp = 225000,
        Beli = 6000
      },
      Task = {
        ["Chief Petty Officer"] = 8
      },
      Name = "Chief Petty Officer",
      LevelReq = 120
    },
    [2] = {
      Reward = {
        Exp = 415000,
        Beli = 15000
      },
      Task = {
        ["Vice Admiral"] = 1
      },
      Name = "Vice Admiral",
      LevelReq = 130
    }
  },
  NutsIslandQuest = {
    [1] = {
      Reward = {
        Exp = 100000000,
        Beli = 14000
      },
      Task = {
        ["Peanut Scout"] = 8
      },
      Name = "Peanut Scout",
      LevelReq = 2075
    },
    [2] = {
      Reward = {
        Exp = 102500000,
        Beli = 14100
      },
      Task = {
        ["Peanut President"] = 8
      },
      Name = "Peanut President",
      LevelReq = 2100
    }
  },
  AmazonQuest = {
    [1] = {
      Reward = {
        Exp = 58000000,
        Beli = 13000
      },
      Task = {
        ["Dragon Crew Warrior"] = 8
      },
      Name = "Dragon Crew Warrior",
      LevelReq = 1575
    },
    [2] = {
      Reward = {
        Exp = 60500000,
        Beli = 15000
      },
      Task = {
        ["Dragon Crew Archer"] = 8
      },
      Name = "Dragon Crew Archer",
      LevelReq = 1600
    }
  },
  PiratePortQuest = {
    [1] = {
      Reward = {
        Exp = 53000000,
        Beli = 13000
      },
      Task = {
        ["Pirate Millionaire"] = 8
      },
      Name = "Pirate Millionaire",
      LevelReq = 1500
    },
    [2] = {
      Reward = {
        Exp = 55500000,
        Beli = 15000
      },
      Task = {
        ["Pistol Billionaire"] = 8
      },
      Name = "Pistol Billionaire",
      LevelReq = 1525
    },
    [3] = {
      Reward = {
        Exp = 60000000,
        Beli = 25000
      },
      Task = {
        Stone = 1
      },
      Name = "Stone",
      LevelReq = 1550
    }
  },
  FrostQuest = {
    [1] = {
      Reward = {
        Exp = 41000000,
        Beli = 12250
      },
      Task = {
        ["Arctic Warrior"] = 8
      },
      Name = "Arctic Warrior",
      LevelReq = 1350
    },
    [2] = {
      Reward = {
        Exp = 43000000,
        Beli = 12500
      },
      Task = {
        ["Snow Lurker"] = 8
      },
      Name = "Snow Lurker",
      LevelReq = 1375
    },
    [3] = {
      Reward = {
        Exp = 45000000,
        Beli = 20000
      },
      Task = {
        ["Awakened Ice Admiral"] = 1
      },
      Name = "Ice Admiral",
      LevelReq = 1400
    }
  },
  ["ShipQuest1"] = {
    [1] = {
      Reward = {
        Exp = 33000000,
        Beli = 12250
      },
      Task = {
        ["Ship Deckhand"] = 8
      },
      Name = "Ship Deckhand",
      LevelReq = 1250
    },
    [2] = {
      Reward = {
        Exp = 35500000,
        Beli = 12500
      },
      Task = {
        ["Ship Engineer"] = 8
      },
      Name = "Ship Engineer",
      LevelReq = 1275
    }
  },
  SnowMountainQuest = {
    [1] = {
      Reward = {
        Exp = 22500000,
        Beli = 12250
      },
      Task = {
        ["Snow Trooper"] = 8
      },
      Name = "Snow Trooper",
      LevelReq = 1000
    },
    [2] = {
      Reward = {
        Exp = 24000000,
        Beli = 12500
      },
      Task = {
        ["Winter Warrior"] = 9
      },
      Name = "Winter Warrior",
      LevelReq = 1050
    }
  },
  BartiloQuest = {
    [1] = {
      MeetsRequirements = function(Val1) --[[ MeetsRequirements ]]end,
      Name = "Swan's Raid",
      OnComplete = function(Val1) --[[ OnComplete ]]end,
      Reward = {
        Exp = 35000000,
        Beli = 50000
      },
      Task = {
        ["Swan Pirate"] = 50
      },
      LevelReq = 850
    }
  },
  ["SkyExp1Quest"] = {
    [1] = {
      Reward = {
        Exp = 4250000,
        Beli = 8750
      },
      Task = {
        ["God's Guard"] = 7
      },
      Name = "God's Guard",
      LevelReq = 450
    },
    [2] = {
      Reward = {
        Exp = 5000000,
        Beli = 9000
      },
      Task = {
        Shanda = 9
      },
      Name = "Shanda",
      LevelReq = 475
    },
    [3] = {
      Reward = {
        Exp = 5700000,
        Beli = 15000
      },
      Task = {
        Wysper = 1
      },
      Name = "Wysper",
      LevelReq = 500
    }
  },
  ["BuggyQuest1"] = {
    [1] = {
      Reward = {
        Exp = 13000,
        Beli = 3000
      },
      Task = {
        Pirate = 8
      },
      Name = "Pirates",
      LevelReq = 30
    },
    [2] = {
      Reward = {
        Exp = 22000,
        Beli = 3500
      },
      Task = {
        Brute = 8
      },
      Name = "Brute",
      LevelReq = 40
    },
    [3] = {
      Reward = {
        Exp = 45000,
        Beli = 8000
      },
      Task = {
        Bobby = 1
      },
      Name = "Bobby",
      LevelReq = 55
    }
  }
}
